### ISSUE TITLE
cmd dll

### ISSUE THREAD

**Issue by RaquisDawLn** [b4keSn4ke/Invoke-WinSATBypass#2]
Ive tried making my own dll to spawn a cmd and i cant seem to get mine to function, could someone send me a working one?

**Comment by b4keSn4ke** [comment]
You could try to build your custom DLL with the following project. To make it work with Invoke-WinSATBypass, I will suggest you to build it with the "prxdll_version" template: https://github.com/pokevas/prxdll_templates
